sudo: false
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - gcc
    - g++
    - clang

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - ./home/sylwia89/hello_world/main.cpp
